'use strict';
// Generated by tools/large-campaign.js from tools/large-selection.json. Do not edit.
// Extends TiltStages (loaded first) with the large-floe band: stages 101-160, chapters 11-16.
(function (root) {
  var base = root.TiltStages;
  if (!base) throw new Error('stages-large.js must be loaded after stages.js');
  var CHAPTERS = [
    {
      "number": 11,
      "name": "WIDE FLOE",
      "ja": "ひろい氷",
      "from": 101,
      "to": 110,
      "note": "Larger floes, 5x4 · 5x5 · 6x4 · 6x5. Par 11–14."
    },
    {
      "number": 12,
      "name": "ARCHIPELAGO",
      "ja": "群島",
      "from": 111,
      "to": 120,
      "note": "Larger floes, 5x4 · 5x5 · 6x4 · 6x5 · 6x6. Par 11–16."
    },
    {
      "number": 13,
      "name": "LABYRINTH",
      "ja": "迷路",
      "from": 121,
      "to": 130,
      "note": "Larger floes, 5x4 · 5x5 · 6x4 · 6x6. Par 12–17."
    },
    {
      "number": 14,
      "name": "LONG NIGHT",
      "ja": "長い夜",
      "from": 131,
      "to": 140,
      "note": "Larger floes, 5x5 · 6x4 · 6x5. Par 11–18."
    },
    {
      "number": 15,
      "name": "DEEP FREEZE",
      "ja": "氷結",
      "from": 141,
      "to": 150,
      "note": "Larger floes, 6x4 · 6x5 · 6x6. Par 12–29."
    },
    {
      "number": 16,
      "name": "THE POLE",
      "ja": "極点",
      "from": 151,
      "to": 160,
      "note": "Larger floes, 6x6. Par 31–44."
    }
  ];
  var STAGES = [
    {
      "id": 101,
      "name": "ICEBOUND",
      "par": 11,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "ba.B.",
        "..##.",
        ".#.A.",
        "..#..",
        "....."
      ]
    },
    {
      "id": 102,
      "name": "SKERRY",
      "par": 11,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "b....",
        "a.#..",
        "B#.A.",
        "....#"
      ]
    },
    {
      "id": 103,
      "name": "FELL",
      "par": 13,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "baB..",
        "..##.",
        ".#.A.",
        ".#...",
        "...#."
      ]
    },
    {
      "id": 104,
      "name": "ESKER",
      "par": 11,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "......",
        "...A#B",
        ".###..",
        "..#..a",
        ".....b"
      ]
    },
    {
      "id": 105,
      "name": "OXBOW",
      "par": 12,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "###A.",
        ".....",
        ".#..b",
        "a....",
        ".B###"
      ]
    },
    {
      "id": 106,
      "name": "KETTLE",
      "par": 11,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "##.b..",
        "..a.#.",
        "......",
        "A##B.#",
        ".....#"
      ]
    },
    {
      "id": 107,
      "name": "DRUMLIN",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        ".A..#",
        "..#..",
        "..##.",
        ".##.a",
        "..B.b"
      ]
    },
    {
      "id": 108,
      "name": "TARN",
      "par": 13,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "#.a..",
        "#...#",
        "....#",
        "#.#AB",
        ".b..#"
      ]
    },
    {
      "id": 109,
      "name": "COL",
      "par": 12,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "##.a.B",
        ".#...#",
        ".A.#.#",
        "#.b..#"
      ]
    },
    {
      "id": 110,
      "name": "ARETE",
      "par": 12,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "#....#",
        "#..#.A",
        "..#.b#",
        "#.B.a#"
      ]
    },
    {
      "id": 111,
      "name": "SASTRUGI",
      "par": 13,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "...##",
        "#..B.",
        "..b#.",
        "#aA.."
      ]
    },
    {
      "id": 112,
      "name": "NEVE",
      "par": 12,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "##A#.",
        "....b",
        "a.##B",
        ".....",
        ".##.#"
      ]
    },
    {
      "id": 113,
      "name": "FIRN",
      "par": 11,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        ".b###.",
        ".a.#..",
        "......",
        "..#.B.",
        "..#...",
        "#...A#"
      ]
    },
    {
      "id": 114,
      "name": "TALUS",
      "par": 12,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "#..b.",
        "B.#..",
        "#..A#",
        "..a.#"
      ]
    },
    {
      "id": 115,
      "name": "SCREE",
      "par": 13,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "..#..b",
        "#A#a##",
        "B.#...",
        "......",
        "#..#.#"
      ]
    },
    {
      "id": 116,
      "name": "PINGO",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "...#..",
        ".#.A..",
        "..#.#.",
        "ba..B."
      ]
    },
    {
      "id": 117,
      "name": "FJELD",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "#.a..#",
        "#...#.",
        "#.#.AB",
        ".b..##"
      ]
    },
    {
      "id": 118,
      "name": "LEEWARD",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "#....",
        "#.##a",
        "..##.",
        ".#B.b",
        "A..##"
      ]
    },
    {
      "id": 119,
      "name": "WINDWARD",
      "par": 15,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "abA.#.",
        "..#.#B",
        ".#....",
        "...#.."
      ]
    },
    {
      "id": 120,
      "name": "PERIGEE",
      "par": 16,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "#....#",
        "#..#b.",
        "B#A#..",
        "...#a#"
      ]
    },
    {
      "id": 121,
      "name": "KELVIN",
      "par": 13,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        ".A###",
        "b....",
        ".##.a",
        "..B..",
        "##.#."
      ]
    },
    {
      "id": 122,
      "name": "ARCTIC",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "#.A#.",
        "...#B",
        ".#...",
        "..b..",
        "#.a##"
      ]
    },
    {
      "id": 123,
      "name": "ALPINE",
      "par": 12,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "#.###",
        "...bA",
        "...#B",
        "##.#a"
      ]
    },
    {
      "id": 124,
      "name": "TAIGA",
      "par": 15,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "....ab",
        ".B##..",
        "....#.",
        "..#..A"
      ]
    },
    {
      "id": 125,
      "name": "STEPPE",
      "par": 17,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "...#.#",
        "B#..b.",
        "A#....",
        "....#a"
      ]
    },
    {
      "id": 126,
      "name": "MESA",
      "par": 13,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "abA.#.",
        "..#...",
        ".###B.",
        "......"
      ]
    },
    {
      "id": 127,
      "name": "BUTTE",
      "par": 13,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "##....",
        "..b.#.",
        "......",
        "B.#aA#"
      ]
    },
    {
      "id": 128,
      "name": "GORGE",
      "par": 15,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "#.a..#",
        "#...#B",
        "A.#...",
        ".b..##"
      ]
    },
    {
      "id": 129,
      "name": "RAVINE",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        ".B..#",
        ".##..",
        ".A##.",
        "#a.b."
      ]
    },
    {
      "id": 130,
      "name": "CIRRUS",
      "par": 15,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "#.....",
        "#..A.#",
        ".b.#..",
        ".a.#..",
        ".#..#B",
        "....#."
      ]
    },
    {
      "id": 131,
      "name": "HALO",
      "par": 13,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "#.....",
        "....#b",
        "..#.A.",
        "..B.#a"
      ]
    },
    {
      "id": 132,
      "name": "SWELL",
      "par": 13,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        ".A#...",
        ".##a#.",
        "...B..",
        "..#b#."
      ]
    },
    {
      "id": 133,
      "name": "DEW",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "..#a.",
        ".#.b#",
        ".##..",
        "B....",
        "#..A#"
      ]
    },
    {
      "id": 134,
      "name": "FOG",
      "par": 15,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "B...#",
        ".##.#",
        "..#..",
        "#A##.",
        "#a.b."
      ]
    },
    {
      "id": 135,
      "name": "SNOWFALL",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        ".b#.#B",
        "A.#...",
        "#....#",
        "#.a..#"
      ]
    },
    {
      "id": 136,
      "name": "DRIZZLE",
      "par": 13,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        ".#.Bab",
        ".A.#..",
        "..###.",
        "..##..",
        "......"
      ]
    },
    {
      "id": 137,
      "name": "VERGLAS",
      "par": 18,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "#...#a",
        "..#A#.",
        ".#..#b",
        "B#...."
      ]
    },
    {
      "id": 138,
      "name": "SLUSH",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "#.#...",
        "..##..",
        "A....#",
        "aB.b.#",
        "##...#"
      ]
    },
    {
      "id": 139,
      "name": "BRASH",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "...B#",
        "#.#..",
        "#.#.A",
        "...a.",
        ".#.b#"
      ]
    },
    {
      "id": 140,
      "name": "FLURRY",
      "par": 11,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "bBaA##",
        "......",
        "#..#..",
        "......",
        ".##..."
      ]
    },
    {
      "id": 141,
      "name": "SHEEN",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "A.B#..",
        "....#.",
        ".##...",
        "a..b.#",
        "#....."
      ]
    },
    {
      "id": 142,
      "name": "HOARFROST",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        ".#..ba",
        ".B.#..",
        "....#A",
        ".##.#.",
        "......"
      ]
    },
    {
      "id": 143,
      "name": "ICICLE",
      "par": 12,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "#..#.b",
        "#...#.",
        "..B...",
        ".#A.a.",
        "...###"
      ]
    },
    {
      "id": 144,
      "name": "GLAZE",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "......",
        "B#A.#.",
        "..#...",
        "ba...#"
      ]
    },
    {
      "id": 145,
      "name": "SEAM",
      "par": 14,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "...A.#",
        "...#..",
        ".#.B#.",
        ".#b.a."
      ]
    },
    {
      "id": 146,
      "name": "SPLINTER",
      "par": 20,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        ".....#",
        "...##.",
        "A#..#.",
        "B.#...",
        "...#.b",
        "##a..."
      ]
    },
    {
      "id": 147,
      "name": "WEDGE",
      "par": 24,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "..B..#",
        "..##..",
        "A##...",
        "..#.#.",
        "..#...",
        "ab.#.."
      ]
    },
    {
      "id": 148,
      "name": "GAP",
      "par": 27,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "...#.#",
        ".#Ba.b",
        "..##.#",
        "#A....",
        "#...#."
      ]
    },
    {
      "id": 149,
      "name": "SPLIT",
      "par": 28,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        ".#..B.",
        "A...#.",
        "#.#..#",
        "...#.a",
        ".#.##.",
        "....b."
      ]
    },
    {
      "id": 150,
      "name": "LEAD",
      "par": 29,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "#....#",
        "...#..",
        "...#..",
        ".#a.#.",
        ".Ab#B.",
        "..##.."
      ]
    },
    {
      "id": 151,
      "name": "POLYNYA",
      "par": 31,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "b.##..",
        "#a.##A",
        "..#...",
        ".B.#..",
        "...#..",
        "##...#"
      ]
    },
    {
      "id": 152,
      "name": "CHIP",
      "par": 32,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "...#..",
        ".#...#",
        ".#..#a",
        ".####A",
        "....#b",
        "#B...."
      ]
    },
    {
      "id": 153,
      "name": "RIFT",
      "par": 33,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "...#..",
        ".#....",
        "A###.#",
        ".#.#..",
        "....##",
        "#.B.ab"
      ]
    },
    {
      "id": 154,
      "name": "FRACTURE",
      "par": 35,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        ".b....",
        ".#..#.",
        "a.#B..",
        "#..#.#",
        ".#....",
        "...A.."
      ]
    },
    {
      "id": 155,
      "name": "CLEAVE",
      "par": 36,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        ".##b..",
        "B...#a",
        "##.#..",
        "...#..",
        ".#...#",
        "...A##"
      ]
    },
    {
      "id": 156,
      "name": "TREMOR",
      "par": 38,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "##B..A",
        "#...#.",
        "..##.b",
        "..#.#a",
        ".#...#",
        "...#.#"
      ]
    },
    {
      "id": 157,
      "name": "QUAKE",
      "par": 39,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "a..b.#",
        "##....",
        "..#A#.",
        "...#B.",
        ".#..#.",
        "..#..."
      ]
    },
    {
      "id": 158,
      "name": "GROWLER",
      "par": 41,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "おたがいに一度ずつ、相手の足場になります。",
        "en": "Each penguin has to stop the other at least once."
      },
      "board": [
        "..#..#",
        ".....#",
        "#..#..",
        "##.##B",
        "#.b.#.",
        "a..#A."
      ]
    },
    {
      "id": 159,
      "name": "BERGY",
      "par": 43,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
        "en": "Being able to collect is not a reason to. Check the partner still has a brake."
      },
      "board": [
        "....#.",
        ".#..A.",
        "..##.#",
        "#...##",
        "##baB.",
        "......"
      ]
    },
    {
      "id": 160,
      "name": "RUPTURE",
      "par": 44,
      "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
      "hint": {
        "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
        "en": "Park the other penguin just past an aurora to stop on it."
      },
      "board": [
        "a.#..A",
        ".b..#.",
        "#.####",
        "..#...",
        ".#.B.#",
        "...#.."
      ]
    }
  ];
  if (!base.STAGES.some(function (s) { return s.id === STAGES[0].id; })) {
    base.STAGES.push.apply(base.STAGES, STAGES);
    (base.CHAPTERS = base.CHAPTERS || []).push.apply(base.CHAPTERS, CHAPTERS);
  }
  root.TiltLargeStages = { STAGES: STAGES, CHAPTERS: CHAPTERS };
})(typeof globalThis !== 'undefined' ? globalThis : this);
