'use strict';
// Generated by tools/cracked-campaign.js from tools/hazard-campaign.json. Do not edit.
// Extends TiltStages (loaded first) with the cracked-ice band: stages 101-160, chapters 11-16.
(function (root) {
  var base = root.TiltStages;
  if (!base) throw new Error('stages-cracked.js must be loaded after stages.js');
  var CHAPTERS = [
    {
      "number": 11,
      "name": "THIN ICE",
      "ja": "うす氷",
      "from": 101,
      "to": 110,
      "extreme": true,
      "note": "Cracked ice: sliding across it is safe, stopping on it is not. Par 12–15."
    },
    {
      "number": 12,
      "name": "HAIRLINE",
      "ja": "ひび",
      "from": 111,
      "to": 120,
      "extreme": true,
      "note": "Longer routes, with cracks in the way. Par 16–21."
    },
    {
      "number": 13,
      "name": "FAULT LINE",
      "ja": "断層",
      "from": 121,
      "to": 130,
      "extreme": true,
      "note": "Floes of every size, from 4×4 to 6×6. Par 21–25."
    },
    {
      "number": 14,
      "name": "SHATTER",
      "ja": "砕氷",
      "from": 131,
      "to": 140,
      "extreme": true,
      "note": "Routes past twenty-five moves. Par 26–32."
    },
    {
      "number": 15,
      "name": "CALVING",
      "ja": "氷河の割れ目",
      "from": 141,
      "to": 150,
      "extreme": true,
      "note": "Routes past thirty moves. Par 32–39."
    },
    {
      "number": 16,
      "name": "ABYSS",
      "ja": "深淵",
      "from": 151,
      "to": 160,
      "extreme": true,
      "note": "The longest cracked-ice routes found. Par 40–54."
    }
  ];
  var STAGES = [
    {
      "id": 101,
      "name": "GLAZE",
      "par": 12,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷の上で止まると失敗。通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice breaks if you stop on it. Sliding across is safe."
      },
      "board": [
        ".###.#",
        "ab..x.",
        "....#.",
        "###.Ax",
        "..#x..",
        "B...#."
      ]
    },
    {
      "id": 102,
      "name": "VERGLAS",
      "par": 12,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        ".a..x.",
        ".#A..B",
        "x...#.",
        "b..#..",
        "#.#..#"
      ]
    },
    {
      "id": 103,
      "name": "SLUSH",
      "par": 12,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "#a...",
        "#BxA.",
        "b#...",
        "...#.",
        "#.x.."
      ]
    },
    {
      "id": 104,
      "name": "BRASH",
      "par": 12,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "...#x",
        "a#...",
        "x.xA#",
        "b#B.#"
      ]
    },
    {
      "id": 105,
      "name": "FLURRY",
      "par": 12,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "..A.",
        ".B#b",
        "#x.x",
        "..#a"
      ]
    },
    {
      "id": 106,
      "name": "CIRRUS",
      "par": 14,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "xb#..#",
        "..x..a",
        "#A.#..",
        ".xB..#",
        "..#..#"
      ]
    },
    {
      "id": 107,
      "name": "SHEEN",
      "par": 14,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "#.....",
        "Ax.##.",
        "..##.#",
        "#.x...",
        ".bB.#.",
        ".ax.#."
      ]
    },
    {
      "id": 108,
      "name": "HOARFROST",
      "par": 14,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "#..B",
        "#x..",
        ".A#b",
        "ax.."
      ]
    },
    {
      "id": 109,
      "name": "ICICLE",
      "par": 15,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "..#ax",
        "#..b.",
        "#x.B#",
        "...A#",
        "#...#"
      ]
    },
    {
      "id": 110,
      "name": "DRIZZLE",
      "par": 15,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        ".A.#b",
        "#Bx.x",
        "...#a",
        "x#..."
      ]
    },
    {
      "id": 111,
      "name": "SEAM",
      "par": 16,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷の上で止まると失敗。通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice breaks if you stop on it. Sliding across is safe."
      },
      "board": [
        "##.#.b",
        "A#.#..",
        ".#...x",
        ".xB.#a",
        "#.#..."
      ]
    },
    {
      "id": 112,
      "name": "HALO",
      "par": 16,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "#...",
        "..#x",
        ".#BA",
        ".xab"
      ]
    },
    {
      "id": 113,
      "name": "SPLINTER",
      "par": 17,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "#..##.",
        "......",
        ".##...",
        "..Ax#x",
        "#B#.b.",
        "#.x.a#"
      ]
    },
    {
      "id": 114,
      "name": "SWELL",
      "par": 17,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "a.xx.",
        ".b.#.",
        "#B...",
        ".x#.#",
        "#..xA"
      ]
    },
    {
      "id": 115,
      "name": "WEDGE",
      "par": 18,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "#A.B..",
        ".x#..#",
        "#..x..",
        ".a.##.",
        ".bx..."
      ]
    },
    {
      "id": 116,
      "name": "GAP",
      "par": 18,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "b.xx.",
        ".aA#.",
        "#....",
        "#B#.#"
      ]
    },
    {
      "id": 117,
      "name": "SPLIT",
      "par": 19,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "#..#.b",
        "Ax..#.",
        ".#..ax",
        ".x....",
        "B.##.#",
        "..##.."
      ]
    },
    {
      "id": 118,
      "name": "LEAD",
      "par": 19,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "#a.#",
        ".x..",
        "#b#.",
        "#A.B"
      ]
    },
    {
      "id": 119,
      "name": "POLYNYA",
      "par": 20,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "...#x",
        ".#x#.",
        "..A..",
        "b#B..",
        "a.#x#"
      ]
    },
    {
      "id": 120,
      "name": "CHIP",
      "par": 21,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "#...#.",
        "..#x..",
        ".x..#A",
        "##.aB.",
        "b....#"
      ]
    },
    {
      "id": 121,
      "name": "RIFT",
      "par": 21,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷の上で止まると失敗。通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice breaks if you stop on it. Sliding across is safe."
      },
      "board": [
        "B.x..",
        ".#Ab.",
        "...#.",
        "#x##a"
      ]
    },
    {
      "id": 122,
      "name": "FRACTURE",
      "par": 21,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "B.aA",
        "x##.",
        "b.#x",
        "#..."
      ]
    },
    {
      "id": 123,
      "name": "CLEAVE",
      "par": 22,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "#B..#.",
        "...#.b",
        ".A.#.#",
        ".x....",
        "#x..#.",
        "..a..."
      ]
    },
    {
      "id": 124,
      "name": "TREMOR",
      "par": 22,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "...#B",
        ".#...",
        ".Ax.#",
        "#.#..",
        "axb.#"
      ]
    },
    {
      "id": 125,
      "name": "OXBOW",
      "par": 23,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "#.#..b",
        "..#..x",
        "..x.#a",
        ".#.B..",
        ".A.#.#"
      ]
    },
    {
      "id": 126,
      "name": "KETTLE",
      "par": 23,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        ".bx..",
        ".A.#.",
        ".#B#.",
        "a#..."
      ]
    },
    {
      "id": 127,
      "name": "ESKER",
      "par": 23,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        ".#aA",
        "..#.",
        ".bxB",
        "#..#"
      ]
    },
    {
      "id": 128,
      "name": "FIRN",
      "par": 24,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "#..x..",
        "...A#.",
        "b##...",
        "x#..B#",
        "a#.#x.",
        "#....#"
      ]
    },
    {
      "id": 129,
      "name": "NEVE",
      "par": 25,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "#.xB#a",
        "#.#.Ax",
        "..x.#b",
        ".#....",
        "...#x#"
      ]
    },
    {
      "id": 130,
      "name": "TALUS",
      "par": 25,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "#.#..",
        "....#",
        ".ax..",
        ".#..B",
        "b#A#x"
      ]
    },
    {
      "id": 131,
      "name": "RUPTURE",
      "par": 26,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷の上で止まると失敗。通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice breaks if you stop on it. Sliding across is safe."
      },
      "board": [
        "..A.#",
        ".#...",
        ".b.#.",
        "#.xaB"
      ]
    },
    {
      "id": 132,
      "name": "DRUMLIN",
      "par": 27,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "bx.a.#",
        "B.##..",
        "...A.#",
        "###x..",
        "....#.",
        "#....."
      ]
    },
    {
      "id": 133,
      "name": "QUAKE",
      "par": 27,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "x.#...",
        "#.x.#.",
        "...##x",
        "b#....",
        "a#B.A#"
      ]
    },
    {
      "id": 134,
      "name": "GROWLER",
      "par": 27,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "..B.#",
        "x#..a",
        "..x.#",
        "..#b.",
        "...#A"
      ]
    },
    {
      "id": 135,
      "name": "BERGY",
      "par": 29,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "..x.##",
        ".#....",
        "BAx#.#",
        "....#.",
        "..#..a",
        "..#..b"
      ]
    },
    {
      "id": 136,
      "name": "FELL",
      "par": 29,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "#..x..",
        ".b#.A#",
        "Ba..x.",
        "...#.#",
        ".#.#.."
      ]
    },
    {
      "id": 137,
      "name": "SKERRY",
      "par": 29,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "#....",
        "a.##.",
        "#x.B.",
        "#.Ab#"
      ]
    },
    {
      "id": 138,
      "name": "ARETE",
      "par": 30,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "#...#",
        "a.#..",
        "#.x.b",
        "..B#.",
        ".#A.."
      ]
    },
    {
      "id": 139,
      "name": "SASTRUGI",
      "par": 31,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        ".....#",
        "...#ax",
        "A#x..#",
        ".#...b",
        ".##B#."
      ]
    },
    {
      "id": 140,
      "name": "COL",
      "par": 32,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "#B#.A.",
        ".....#",
        "..a.#.",
        "##...x",
        ".x.b..",
        "..##.."
      ]
    },
    {
      "id": 141,
      "name": "TARN",
      "par": 32,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷の上で止まると失敗。通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice breaks if you stop on it. Sliding across is safe."
      },
      "board": [
        "..###",
        "#....",
        "..B#.",
        ".#aA.",
        ".bx.#"
      ]
    },
    {
      "id": 142,
      "name": "FJELD",
      "par": 32,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        ".a##.",
        "#..Ax",
        "B..#b",
        ".#..."
      ]
    },
    {
      "id": 143,
      "name": "PINGO",
      "par": 33,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "B..#.#",
        ".#A...",
        "..x.#.",
        "#.#.#.",
        "#.abx."
      ]
    },
    {
      "id": 144,
      "name": "SCREE",
      "par": 34,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        ".#.B..",
        "x..#x.",
        ".....#",
        "#.#...",
        "A.#.#.",
        "x#axb."
      ]
    },
    {
      "id": 145,
      "name": "DEW",
      "par": 35,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "##.#x#",
        "A#....",
        ".#.a..",
        "..x.##",
        "#.Bxb#"
      ]
    },
    {
      "id": 146,
      "name": "LULL",
      "par": 35,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        ".x..#",
        "#.#..",
        ".b..B",
        "A#...",
        "a#.#x"
      ]
    },
    {
      "id": 147,
      "name": "FOG",
      "par": 37,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "#....#",
        "#.#...",
        "#.b.#.",
        ".#Ax..",
        "xBx#.#",
        "...a.#"
      ]
    },
    {
      "id": 148,
      "name": "ECHO",
      "par": 37,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        ".#x.A",
        "..#..",
        "xab.#",
        ".#...",
        "...#B"
      ]
    },
    {
      "id": 149,
      "name": "VIGIL",
      "par": 38,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "#...#b",
        "#.##..",
        "..x.#.",
        ".#..aB",
        ".A.#x#"
      ]
    },
    {
      "id": 150,
      "name": "SNOWFALL",
      "par": 39,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "##.B..",
        "...A#.",
        "..#..#",
        "#..x..",
        "...##a",
        ".#x.#b"
      ]
    },
    {
      "id": 151,
      "name": "NADIR",
      "par": 40,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷の上で止まると失敗。通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice breaks if you stop on it. Sliding across is safe."
      },
      "board": [
        "##B..#",
        "..##..",
        "....b.",
        "A#...x",
        "#...#a"
      ]
    },
    {
      "id": 152,
      "name": "UMBRA",
      "par": 40,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        "#A...",
        "..b#a",
        ".#..x",
        "..#xB",
        "#...#"
      ]
    },
    {
      "id": 153,
      "name": "WANE",
      "par": 42,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "Abx..#",
        "a.B#.x",
        "###...",
        ".....#",
        "...#x.",
        "#....."
      ]
    },
    {
      "id": 154,
      "name": "DUSK",
      "par": 42,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "A..#..",
        ".#..x.",
        ".##..#",
        "B.b#..",
        "#a#..."
      ]
    },
    {
      "id": 155,
      "name": "LEEWARD",
      "par": 44,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        ".....#",
        "##....",
        "....#a",
        "#..x##",
        "x.#...",
        "B.A.#b"
      ]
    },
    {
      "id": 156,
      "name": "FACET",
      "par": 44,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "#.#..A",
        "#...#a",
        "..#..x",
        "...#..",
        "##Bxb#"
      ]
    },
    {
      "id": 157,
      "name": "WINDWARD",
      "par": 47,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "..#Bab",
        "Ax..##",
        "#..##.",
        "..#...",
        ".#.#..",
        "...x.#"
      ]
    },
    {
      "id": 158,
      "name": "CRYSTAL",
      "par": 49,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "割れる氷は、すべって通り過ぎるだけなら大丈夫です。",
        "en": "Cracked ice is safe to slide across; it breaks only if you stop on it."
      },
      "board": [
        ".A.#..",
        ".#....",
        "...x#b",
        "..x.##",
        "#B#...",
        ".xa.#x"
      ]
    },
    {
      "id": 159,
      "name": "GLACIER",
      "par": 52,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "一度ゴールから遠ざかると、止まれる場所が見えてきます。",
        "en": "Moving away from a goal can reveal a place to stop."
      },
      "board": [
        "..xa.#",
        ".#....",
        "#.....",
        ".A##..",
        "b.B.x#",
        ".#...."
      ]
    },
    {
      "id": 160,
      "name": "PERIGEE",
      "par": 54,
      "idea": "Cracked ice: slide across it, never stop on it.",
      "hint": {
        "ja": "相棒に当たって止まる場所を探してみよう。",
        "en": "Look for a place where one penguin stops against the other."
      },
      "board": [
        "..#A.a",
        ".#...x",
        "..x...",
        "#..#.b",
        "...#..",
        ".#B..#"
      ]
    }
  ];
  if (!base.STAGES.some(function (s) { return s.id === STAGES[0].id; })) {
    base.STAGES.push.apply(base.STAGES, STAGES);
    (base.CHAPTERS = base.CHAPTERS || []).push.apply(base.CHAPTERS, CHAPTERS);
  }
  root.TiltCrackedStages = { STAGES: STAGES, CHAPTERS: CHAPTERS };
})(typeof globalThis !== 'undefined' ? globalThis : this);
