'use strict';
// Generated by tools/floe-campaign.js from tools/floe-selection.json.
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.TiltStages=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  var CHAPTERS = [
  {
    "number": 1,
    "name": "FIRST LIGHT",
    "ja": "はじまり",
    "from": 1,
    "to": 10,
    "note": "Two penguins on one floe; the ice edge and each other are the only brakes."
  },
  {
    "number": 2,
    "name": "PARTNERS",
    "ja": "ふたり",
    "from": 11,
    "to": 20,
    "note": "Two penguins on one floe; the ice edge and each other are the only brakes."
  },
  {
    "number": 3,
    "name": "BRAKES",
    "ja": "止まり木",
    "from": 21,
    "to": 30,
    "note": "Two penguins on one floe; the ice edge and each other are the only brakes."
  },
  {
    "number": 4,
    "name": "CROSSROADS",
    "ja": "分かれ道",
    "from": 31,
    "to": 40,
    "note": "Two penguins on one floe; the ice edge and each other are the only brakes."
  },
  {
    "number": 5,
    "name": "SETUP",
    "ja": "布石",
    "from": 41,
    "to": 50,
    "note": "Two penguins on one floe; the ice edge and each other are the only brakes."
  },
  {
    "number": 6,
    "name": "EXCHANGE",
    "ja": "入れ替え",
    "from": 51,
    "to": 60,
    "note": "Two penguins on one floe; the ice edge and each other are the only brakes."
  },
  {
    "number": 7,
    "name": "BALANCE",
    "ja": "釣り合い",
    "from": 61,
    "to": 70,
    "note": "Two penguins on one floe; the ice edge and each other are the only brakes."
  },
  {
    "number": 8,
    "name": "PATIENCE",
    "ja": "順番",
    "from": 71,
    "to": 80,
    "note": "Two penguins on one floe; the ice edge and each other are the only brakes."
  },
  {
    "number": 9,
    "name": "DISCOVERY",
    "ja": "発見",
    "from": 81,
    "to": 90,
    "note": "Two penguins on one floe; the ice edge and each other are the only brakes."
  },
  {
    "number": 10,
    "name": "FINALE",
    "ja": "結晶",
    "from": 91,
    "to": 100,
    "note": "Two penguins on one floe; the ice edge and each other are the only brakes."
  }
];
  var STAGES = [
  {
    "id": 1,
    "name": "HOME",
    "par": 2,
    "idea": "One penguin; the edge of the ice — the rim or a hole — is the only brake.",
    "hint": {
      "ja": "氷のふちで止まります。オーロラの上で止まれば回収です。",
      "en": "The edge of the ice stops you. Stop on the aurora to collect."
    },
    "board": [
      "##..",
      "...A",
      ".#a.",
      "..##"
    ]
  },
  {
    "id": 2,
    "name": "PAIR",
    "par": 3,
    "idea": "One penguin; the edge of the ice — the rim or a hole — is the only brake.",
    "hint": {
      "ja": "穴のふちでも止まれます。水には落ちません。",
      "en": "A hole stops you just like the outer edge. Nobody falls in."
    },
    "board": [
      "##..",
      "....",
      "..#a",
      ".A##"
    ]
  },
  {
    "id": 3,
    "name": "GLIDE",
    "par": 4,
    "idea": "One penguin; the edge of the ice — the rim or a hole — is the only brake.",
    "hint": {
      "ja": "一度別の場所で止まってから、向きを変えてみよう。",
      "en": "Stop somewhere else first, then change direction."
    },
    "board": [
      "#.#.",
      "....",
      ".#.A",
      "a#.#"
    ]
  },
  {
    "id": 4,
    "name": "FLOE",
    "par": 4,
    "idea": "One penguin must stop the other; a penguin can only be collected by being braked onto its aurora.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "##B#",
      "A.ab",
      "#..#",
      "#.##"
    ]
  },
  {
    "id": 5,
    "name": "CROSS",
    "par": 4,
    "idea": "One penguin must stop the other; a penguin can only be collected by being braked onto its aurora.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "#..#",
      "#A..",
      "ab..",
      "B.##"
    ]
  },
  {
    "id": 6,
    "name": "CALM",
    "par": 5,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "##B#",
      "a.bA",
      "....",
      "#.##"
    ]
  },
  {
    "id": 7,
    "name": "FROST",
    "par": 6,
    "idea": "One penguin must stop the other; a penguin can only be collected by being braked onto its aurora.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "#.ab",
      "..##",
      "..BA",
      "..##"
    ]
  },
  {
    "id": 8,
    "name": "SHELF",
    "par": 5,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "A..a",
      "...b",
      "..#.",
      "#B.#"
    ]
  },
  {
    "id": 9,
    "name": "CRISP",
    "par": 5,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "ab.#",
      "..#.",
      "..B.",
      "A###"
    ]
  },
  {
    "id": 10,
    "name": "DAWN",
    "par": 4,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "A.##",
      ".a#.",
      "B..b",
      ".###"
    ]
  },
  {
    "id": 11,
    "name": "RIME",
    "par": 6,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      ".#..",
      "....",
      "a##A",
      ".b#B"
    ]
  },
  {
    "id": 12,
    "name": "THAW",
    "par": 5,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      ".a#.",
      "..#.",
      ".bB.",
      ".A##"
    ]
  },
  {
    "id": 13,
    "name": "SLEET",
    "par": 6,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "....",
      "BA..",
      "a#..",
      "b#.#"
    ]
  },
  {
    "id": 14,
    "name": "BERG",
    "par": 6,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "##..",
      "B.ab",
      "#A.#",
      "#.##"
    ]
  },
  {
    "id": 15,
    "name": "CRAG",
    "par": 6,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "a.A#",
      "....",
      "b#.B",
      ".#.#"
    ]
  },
  {
    "id": 16,
    "name": "PALE",
    "par": 7,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "#.B#",
      "a..A",
      ".b..",
      "..##"
    ]
  },
  {
    "id": 17,
    "name": "HUSH",
    "par": 7,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "##B#",
      "a..A",
      "b.#.",
      ".###"
    ]
  },
  {
    "id": 18,
    "name": "VEIL",
    "par": 6,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "##.#",
      ".aA#",
      "b..B",
      ".###"
    ]
  },
  {
    "id": 19,
    "name": "SPUR",
    "par": 5,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "#.#.",
      "#..a",
      "bB.A",
      ".###"
    ]
  },
  {
    "id": 20,
    "name": "NORTH",
    "par": 5,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "..ab",
      "B...",
      "A.#.",
      "...."
    ]
  },
  {
    "id": 21,
    "name": "GLEAM",
    "par": 6,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "#B..",
      ".a#A",
      "#...",
      "#b##"
    ]
  },
  {
    "id": 22,
    "name": "SNAP",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "#.#B",
      ".a#A",
      "#...",
      ".b##"
    ]
  },
  {
    "id": 23,
    "name": "RIDGE",
    "par": 6,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "a...",
      "#BAb",
      "....",
      ".###"
    ]
  },
  {
    "id": 24,
    "name": "BASIN",
    "par": 4,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "a##.",
      "AB..",
      ".b..",
      "#.##"
    ]
  },
  {
    "id": 25,
    "name": "FJORD",
    "par": 6,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "a..B",
      "..#.",
      ".b..",
      "A#.#"
    ]
  },
  {
    "id": 26,
    "name": "SHARD",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      ".a.#",
      ".b..",
      "#..B",
      "#A##"
    ]
  },
  {
    "id": 27,
    "name": "PRISM",
    "par": 7,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "ab..",
      "..#.",
      ".##.",
      "A.B."
    ]
  },
  {
    "id": 28,
    "name": "GLINT",
    "par": 5,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "##.B",
      "..ab",
      "...A",
      "#.##"
    ]
  },
  {
    "id": 29,
    "name": "HOAR",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "..a.",
      "....",
      ".A#.",
      "bB##"
    ]
  },
  {
    "id": 30,
    "name": "BLUE",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      ".a.b",
      ".#..",
      "..#.",
      "..AB"
    ]
  },
  {
    "id": 31,
    "name": "CLEFT",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "#a#A",
      "#...",
      ".b.#",
      "#B##"
    ]
  },
  {
    "id": 32,
    "name": "WAKE",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "#a..",
      ".b##",
      "#.AB",
      "#.##"
    ]
  },
  {
    "id": 33,
    "name": "SHOAL",
    "par": 7,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "A...",
      "....",
      "Ba.b",
      "..##"
    ]
  },
  {
    "id": 34,
    "name": "PACK",
    "par": 7,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      ".AB.",
      ".##a",
      "....",
      "..#b"
    ]
  },
  {
    "id": 35,
    "name": "TIDE",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "....",
      "a...",
      "BA..",
      "b#.#"
    ]
  },
  {
    "id": 36,
    "name": "SPIRE",
    "par": 7,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "..##",
      "Ba.b",
      "A...",
      ".###"
    ]
  },
  {
    "id": 37,
    "name": "BRINE",
    "par": 6,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "##A.",
      ".ab#",
      "..B.",
      ".###"
    ]
  },
  {
    "id": 38,
    "name": "CROWN",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "#.ab",
      "..#.",
      "..AB",
      ".###"
    ]
  },
  {
    "id": 39,
    "name": "STILL",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "..#a",
      ".B#.",
      "..b.",
      "A###"
    ]
  },
  {
    "id": 40,
    "name": "FLARE",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "a#..",
      "....",
      "b.#A",
      ".##B"
    ]
  },
  {
    "id": 41,
    "name": "QUARTZ",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "A...",
      "..#a",
      "..Bb",
      "#.##"
    ]
  },
  {
    "id": 42,
    "name": "LEDGE",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "....",
      "..AB",
      ".a.b",
      "#.##"
    ]
  },
  {
    "id": 43,
    "name": "SLATE",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "#..A",
      "Ba.b",
      "..##",
      ".###"
    ]
  },
  {
    "id": 44,
    "name": "MIST",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "....",
      "...#",
      "AaBb",
      "#.##"
    ]
  },
  {
    "id": 45,
    "name": "ARCH",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      ".A.B",
      "..#a",
      "#..b",
      "#.##"
    ]
  },
  {
    "id": 46,
    "name": "FLINT",
    "par": 7,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "#aA#",
      "Bb.#",
      "#...",
      "#.##"
    ]
  },
  {
    "id": 47,
    "name": "GLACE",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "Ba.b",
      ".#.#",
      "A...",
      "..##"
    ]
  },
  {
    "id": 48,
    "name": "SIREN",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      ".a.#",
      "..B.",
      "..bA",
      ".###"
    ]
  },
  {
    "id": 49,
    "name": "HOLLOW",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "...A",
      "...a",
      "...B",
      "..#b"
    ]
  },
  {
    "id": 50,
    "name": "HALF",
    "par": 7,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "#a.A",
      ".b..",
      "..#.",
      ".B##"
    ]
  },
  {
    "id": 51,
    "name": "AURORA",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "Ba.b",
      "...#",
      "....",
      "A##."
    ]
  },
  {
    "id": 52,
    "name": "CINDER",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "#A.B",
      "....",
      "a##b",
      "...#"
    ]
  },
  {
    "id": 53,
    "name": "BEACON",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "a..A",
      "##..",
      ".#.B",
      ".b.#"
    ]
  },
  {
    "id": 54,
    "name": "LANTERN",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "#.#a",
      "..#b",
      ".B.A",
      ".###"
    ]
  },
  {
    "id": 55,
    "name": "HARBOUR",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "#.B.",
      "a.A.",
      ".b..",
      "..##"
    ]
  },
  {
    "id": 56,
    "name": "KEEL",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "a..B",
      "b..#",
      "A#..",
      ".#.#"
    ]
  },
  {
    "id": 57,
    "name": "ANCHOR",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "aA..",
      "....",
      "b##.",
      "..B."
    ]
  },
  {
    "id": 58,
    "name": "MARINER",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "....",
      "a#A#",
      "B#..",
      "b.#."
    ]
  },
  {
    "id": 59,
    "name": "COMPASS",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "#AB.",
      ".a#.",
      "#...",
      ".b##"
    ]
  },
  {
    "id": 60,
    "name": "MERIDIAN",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "..B.",
      "#.#a",
      "#..b",
      "A.##"
    ]
  },
  {
    "id": 61,
    "name": "SOLSTICE",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "..B.",
      "..A.",
      "a##.",
      "..b#"
    ]
  },
  {
    "id": 62,
    "name": "ZENITH",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "A...",
      ".#.a",
      "B..b",
      "..##"
    ]
  },
  {
    "id": 63,
    "name": "LATITUDE",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      ".a.b",
      "B###",
      "....",
      ".##A"
    ]
  },
  {
    "id": 64,
    "name": "CURRENT",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "..a.",
      "..#.",
      "#A#b",
      "#B##"
    ]
  },
  {
    "id": 65,
    "name": "DRAUGHT",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "abA.",
      "B..#",
      "....",
      ".#.#"
    ]
  },
  {
    "id": 66,
    "name": "CAVERN",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "...A",
      "...B",
      ".#..",
      ".ab#"
    ]
  },
  {
    "id": 67,
    "name": "CHASM",
    "par": 12,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "....",
      "a#..",
      "B#..",
      "b#A#"
    ]
  },
  {
    "id": 68,
    "name": "FISSURE",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "a.b.",
      ".##.",
      ".#..",
      "A.B#"
    ]
  },
  {
    "id": 69,
    "name": "MORAINE",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      ".A..",
      "a#..",
      "B...",
      "b#.#"
    ]
  },
  {
    "id": 70,
    "name": "CIRQUE",
    "par": 12,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      ".aBb",
      ".###",
      "..A.",
      "..##"
    ]
  },
  {
    "id": 71,
    "name": "SERAC",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      ".A#a",
      ".B#.",
      "..b.",
      ".#.#"
    ]
  },
  {
    "id": 72,
    "name": "CREVASSE",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "#..A",
      ".a.#",
      "#.B.",
      ".b##"
    ]
  },
  {
    "id": 73,
    "name": "CORNICE",
    "par": 12,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "B.ab",
      ".#.#",
      "....",
      "A#.#"
    ]
  },
  {
    "id": 74,
    "name": "SUMMIT",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "a#.A",
      ".#.B",
      ".b..",
      "#.##"
    ]
  },
  {
    "id": 75,
    "name": "TRAVERSE",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "#...",
      "ab.A",
      "#.##",
      ".B##"
    ]
  },
  {
    "id": 76,
    "name": "ASCENT",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      ".##.",
      "B#A.",
      "ab..",
      "#.##"
    ]
  },
  {
    "id": 77,
    "name": "PITON",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "a..A",
      "....",
      "b.#.",
      ".B#."
    ]
  },
  {
    "id": 78,
    "name": "BELAY",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      ".#.#",
      "a.bB",
      "....",
      "#A##"
    ]
  },
  {
    "id": 79,
    "name": "CAIRN",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "a...",
      "bA#.",
      "....",
      "#.B#"
    ]
  },
  {
    "id": 80,
    "name": "BEARING",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "##..",
      "a##.",
      ".bBA",
      "#.##"
    ]
  },
  {
    "id": 81,
    "name": "POLARIS",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "..Aa",
      "..#b",
      "B#..",
      "...#"
    ]
  },
  {
    "id": 82,
    "name": "MIDNIGHT",
    "par": 12,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "....",
      "#.#a",
      "AB#.",
      "..#b"
    ]
  },
  {
    "id": 83,
    "name": "LONGNIGHT",
    "par": 9,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "a..A",
      "..#.",
      ".b..",
      "B###"
    ]
  },
  {
    "id": 84,
    "name": "WHITEOUT",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "#A##",
      ".a..",
      "B...",
      "b###"
    ]
  },
  {
    "id": 85,
    "name": "BLIZZARD",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "B.#a",
      ".##b",
      "A...",
      "#..#"
    ]
  },
  {
    "id": 86,
    "name": "SQUALL",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      ".A..",
      "#.#a",
      "..#B",
      ".##b"
    ]
  },
  {
    "id": 87,
    "name": "TEMPEST",
    "par": 8,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "..B.",
      "#...",
      "abA.",
      "..##"
    ]
  },
  {
    "id": 88,
    "name": "GALE",
    "par": 12,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "B..#",
      "A##a",
      ".b..",
      "#.##"
    ]
  },
  {
    "id": 89,
    "name": "PASSAGE",
    "par": 13,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "....",
      "..#a",
      "#B..",
      ".A#b"
    ]
  },
  {
    "id": 90,
    "name": "ICEFALL",
    "par": 12,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      "....",
      "A.#a",
      "#.#B",
      "..#b"
    ]
  },
  {
    "id": 91,
    "name": "DEEPFROST",
    "par": 12,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 3 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "....",
      ".#..",
      "a#AB",
      "..b#"
    ]
  },
  {
    "id": 92,
    "name": "COLDIRON",
    "par": 12,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "..a.",
      "A.#.",
      "b...",
      "B.##"
    ]
  },
  {
    "id": 93,
    "name": "STARFIELD",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      ".B#A",
      ".#..",
      "ab..",
      "#.##"
    ]
  },
  {
    "id": 94,
    "name": "NIGHTFALL",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "#abA",
      "B##.",
      "....",
      "#.##"
    ]
  },
  {
    "id": 95,
    "name": "FARSHORE",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      ".a.#",
      ".bB#",
      "#...",
      "#A##"
    ]
  },
  {
    "id": 96,
    "name": "LASTLIGHT",
    "par": 11,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "もう一羽をオーロラの先に置くと、その上で止まれます。",
      "en": "Park the other penguin just past an aurora to stop on it."
    },
    "board": [
      ".##a",
      "A.b.",
      "#..#",
      "#B##"
    ]
  },
  {
    "id": 97,
    "name": "ENDLESS",
    "par": 12,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 1 fatal early collection on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "#A##",
      "Ba..",
      "...#",
      "b###"
    ]
  },
  {
    "id": 98,
    "name": "THRESHOLD",
    "par": 12,
    "idea": "Each penguin must stop the other at least once; a penguin can only be collected by being braked onto its aurora; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "回収できても、すぐに入れるとは限りません。相手の足場が残っているか確かめよう。",
      "en": "Being able to collect is not a reason to. Check the partner still has a brake."
    },
    "board": [
      "#.a.",
      "B##.",
      "b...",
      ".A##"
    ]
  },
  {
    "id": 99,
    "name": "CROSSING",
    "par": 10,
    "idea": "Each penguin must stop the other at least once; 3 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "一度オーロラから遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away from an aurora can reveal a new place to stop."
    },
    "board": [
      "A#a#",
      "b.B.",
      "#...",
      "..##"
    ]
  },
  {
    "id": 100,
    "name": "TILT",
    "par": 12,
    "idea": "Each penguin must stop the other at least once; 2 fatal early collections on the shortest routes.",
    "hint": {
      "ja": "おたがいに一度ずつ、相手の足場になります。",
      "en": "Each penguin has to stop the other at least once."
    },
    "board": [
      "...A",
      ".#..",
      "..ab",
      "#B##"
    ]
  }
];
  return { STAGES:STAGES, CHAPTERS:CHAPTERS };
});
