'use strict';
// Generated by tools/refresh-campaign.js from the reviewed campaign-selection.json.
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.TiltStages=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  var CHAPTERS = [
  {
    "number": 1,
    "name": "FIRST LIGHT",
    "ja": "はじまり",
    "from": 1,
    "to": 10,
    "note": "Two penguins, shared gravity, and a choice of paths."
  },
  {
    "number": 2,
    "name": "PARTNERS",
    "ja": "ふたり",
    "from": 11,
    "to": 20,
    "note": "Two penguins, shared gravity, and a choice of paths."
  },
  {
    "number": 3,
    "name": "BRAKES",
    "ja": "止まり木",
    "from": 21,
    "to": 30,
    "note": "Two penguins, shared gravity, and a choice of paths."
  },
  {
    "number": 4,
    "name": "CROSSROADS",
    "ja": "分かれ道",
    "from": 31,
    "to": 40,
    "note": "Two penguins, shared gravity, and a choice of paths."
  },
  {
    "number": 5,
    "name": "SETUP",
    "ja": "布石",
    "from": 41,
    "to": 50,
    "note": "Two penguins, shared gravity, and a choice of paths."
  },
  {
    "number": 6,
    "name": "EXCHANGE",
    "ja": "入れ替え",
    "from": 51,
    "to": 60,
    "note": "Two penguins, shared gravity, and a choice of paths."
  },
  {
    "number": 7,
    "name": "BALANCE",
    "ja": "釣り合い",
    "from": 61,
    "to": 70,
    "note": "Two penguins, shared gravity, and a choice of paths."
  },
  {
    "number": 8,
    "name": "PATIENCE",
    "ja": "順番",
    "from": 71,
    "to": 80,
    "note": "Two penguins, shared gravity, and a choice of paths."
  },
  {
    "number": 9,
    "name": "DISCOVERY",
    "ja": "発見",
    "from": 81,
    "to": 90,
    "note": "Two penguins, shared gravity, and a choice of paths."
  },
  {
    "number": 10,
    "name": "FINALE",
    "ja": "結晶",
    "from": 91,
    "to": 100,
    "note": "Two penguins, shared gravity, and a choice of paths."
  }
];
  var STAGES = [
  {
    "id": 1,
    "name": "HOME",
    "par": 3,
    "idea": "One penguin; learn to stop on the aurora.",
    "hint": {
      "ja": "壁で止まって、オーロラを目指そう。通り過ぎるだけでは入れません。",
      "en": "Use the wall to stop on your aurora. Passing over it does not collect you."
    },
    "board": [
      "#a..",
      "A...",
      "....",
      "...."
    ]
  },
  {
    "id": 2,
    "name": "PAIR",
    "par": 3,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "2体が同時に滑ります。それぞれ同じ色のオーロラへ。",
      "en": "Both penguins slide together. Stop each on its matching aurora."
    },
    "board": [
      "..#.",
      ".##B",
      "#..b",
      "#.Aa"
    ]
  },
  {
    "id": 3,
    "name": "GLIDE",
    "par": 3,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "もう一羽も、止まるための足場になります。",
      "en": "The other penguin can be the brake you need."
    },
    "board": [
      "##.#",
      ".B..",
      "...A",
      "##ba"
    ]
  },
  {
    "id": 4,
    "name": "FLOE",
    "par": 4,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "a#A#",
      "b...",
      ".B.#",
      ".##."
    ]
  },
  {
    "id": 5,
    "name": "CROSS",
    "par": 4,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "もう一羽も、止まるための足場になります。",
      "en": "The other penguin can be the brake you need."
    },
    "board": [
      "##..",
      ".#..",
      "...B",
      ".Aab"
    ]
  },
  {
    "id": 6,
    "name": "CALM",
    "par": 4,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "もう一羽も、止まるための足場になります。",
      "en": "The other penguin can be the brake you need."
    },
    "board": [
      ".Aa#",
      "..b#",
      "#.B#",
      "...#"
    ]
  },
  {
    "id": 7,
    "name": "FROST",
    "par": 4,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "もう一羽も、止まるための足場になります。",
      "en": "The other penguin can be the brake you need."
    },
    "board": [
      "#...",
      ".#.A",
      "...a",
      "#.Bb"
    ]
  },
  {
    "id": 8,
    "name": "SHELF",
    "par": 5,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "もう一羽も、止まるための足場になります。",
      "en": "The other penguin can be the brake you need."
    },
    "board": [
      ".A##",
      "B..#",
      "b...",
      "a##."
    ]
  },
  {
    "id": 9,
    "name": "CRISP",
    "par": 5,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#a..",
      "#B.#",
      "b.##",
      ".A.."
    ]
  },
  {
    "id": 10,
    "name": "DAWN",
    "par": 5,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "##.#",
      "..A.",
      "ba..",
      "B.##"
    ]
  },
  {
    "id": 11,
    "name": "RIME",
    "par": 5,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "##a.",
      "bAB.",
      "..#.",
      "..#."
    ]
  },
  {
    "id": 12,
    "name": "THAW",
    "par": 6,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "もう一羽も、止まるための足場になります。",
      "en": "The other penguin can be the brake you need."
    },
    "board": [
      "...#",
      "a#A.",
      "#..#",
      "#.bB"
    ]
  },
  {
    "id": 13,
    "name": "SLEET",
    "par": 6,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "..#a",
      ".#..",
      "A.B.",
      ".b#."
    ]
  },
  {
    "id": 14,
    "name": "BERG",
    "par": 6,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "bA#.",
      "....",
      ".B.#",
      "a###"
    ]
  },
  {
    "id": 15,
    "name": "CRAG",
    "par": 6,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "b.A.",
      ".#.#",
      "##Ba",
      "...."
    ]
  },
  {
    "id": 16,
    "name": "PALE",
    "par": 6,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".a#b",
      "B.A.",
      ".#..",
      ".#.#"
    ]
  },
  {
    "id": 17,
    "name": "HUSH",
    "par": 7,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "#..b",
      "#.BA",
      "...a",
      ".#.."
    ]
  },
  {
    "id": 18,
    "name": "VEIL",
    "par": 7,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "b###",
      ".#.#",
      "A.Ba",
      "...."
    ]
  },
  {
    "id": 19,
    "name": "SPUR",
    "par": 7,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "b#.#",
      "A.Ba",
      "....",
      "...."
    ]
  },
  {
    "id": 20,
    "name": "NORTH",
    "par": 7,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "....",
      "A.Ba",
      "b#.#",
      "#.##"
    ]
  },
  {
    "id": 21,
    "name": "GLEAM",
    "par": 8,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#.Ab",
      "..a#",
      ".#.#",
      "..B."
    ]
  },
  {
    "id": 22,
    "name": "SNAP",
    "par": 8,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "..A.",
      "Bb.#",
      "#...",
      "#a##"
    ]
  },
  {
    "id": 23,
    "name": "RIDGE",
    "par": 8,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "..Ab",
      "B#.#",
      "...a",
      "##.."
    ]
  },
  {
    "id": 24,
    "name": "BASIN",
    "par": 8,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "b.A#",
      "a#.#",
      "...#",
      "B.#."
    ]
  },
  {
    "id": 25,
    "name": "FJORD",
    "par": 8,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".a.b",
      ".###",
      ".AB.",
      "...."
    ]
  },
  {
    "id": 26,
    "name": "SHARD",
    "par": 9,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#.#b",
      "#.B.",
      "#A#a",
      "...."
    ]
  },
  {
    "id": 27,
    "name": "PRISM",
    "par": 9,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".A#a",
      ".##.",
      "B.#b",
      "...."
    ]
  },
  {
    "id": 28,
    "name": "GLINT",
    "par": 9,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".##.",
      "#A#B",
      "....",
      "b#a."
    ]
  },
  {
    "id": 29,
    "name": "HOAR",
    "par": 9,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "A...",
      ".B#.",
      ".#b.",
      "#a.#"
    ]
  },
  {
    "id": 30,
    "name": "BLUE",
    "par": 10,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "..A.",
      "..a#",
      ".#..",
      ".b#B"
    ]
  },
  {
    "id": 31,
    "name": "CLEFT",
    "par": 10,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#.##",
      ".b.a",
      ".A#.",
      "B..."
    ]
  },
  {
    "id": 32,
    "name": "WAKE",
    "par": 10,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "#...",
      "B.#a",
      "....",
      "bA##"
    ]
  },
  {
    "id": 33,
    "name": "SHOAL",
    "par": 10,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "B...",
      "b##.",
      ".#..",
      "a#A#"
    ]
  },
  {
    "id": 34,
    "name": "PACK",
    "par": 11,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "B..#",
      ".#..",
      ".##A",
      ".ba#"
    ]
  },
  {
    "id": 35,
    "name": "TIDE",
    "par": 11,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "a###",
      "..b.",
      "A.#B",
      "#..."
    ]
  },
  {
    "id": 36,
    "name": "SPIRE",
    "par": 11,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#A.#",
      ".B..",
      "a##.",
      "b#.."
    ]
  },
  {
    "id": 37,
    "name": "BRINE",
    "par": 11,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "..B#",
      "A#..",
      "###.",
      "a.b."
    ]
  },
  {
    "id": 38,
    "name": "CROWN",
    "par": 11,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".#A#",
      "#a..",
      "b.#B",
      "#..."
    ]
  },
  {
    "id": 39,
    "name": "STILL",
    "par": 12,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".B.b",
      ".#.a",
      "A.#.",
      "...."
    ]
  },
  {
    "id": 40,
    "name": "FLARE",
    "par": 12,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "aBb.",
      "..#.",
      "....",
      "A###"
    ]
  },
  {
    "id": 41,
    "name": "QUARTZ",
    "par": 12,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "..B.",
      ".A##",
      "#b#.",
      "a.#."
    ]
  },
  {
    "id": 42,
    "name": "LEDGE",
    "par": 12,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#..A",
      "b.#.",
      "#...",
      "Ba##"
    ]
  },
  {
    "id": 43,
    "name": "SLATE",
    "par": 13,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "A...",
      ".#..",
      "B#b#",
      "##.a"
    ]
  },
  {
    "id": 44,
    "name": "MIST",
    "par": 13,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#A.#",
      "....",
      ".##B",
      "#ba."
    ]
  },
  {
    "id": 45,
    "name": "ARCH",
    "par": 13,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "#A..",
      "aB#.",
      "##..",
      "..#b"
    ]
  },
  {
    "id": 46,
    "name": "FLINT",
    "par": 13,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "#.#a",
      "....",
      "BA##",
      "...b"
    ]
  },
  {
    "id": 47,
    "name": "GLACE",
    "par": 13,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".b.B",
      "..#.",
      "a..A",
      "###."
    ]
  },
  {
    "id": 48,
    "name": "SIREN",
    "par": 14,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "B..#",
      ".#..",
      ".A#.",
      "#ab."
    ]
  },
  {
    "id": 49,
    "name": "HOLLOW",
    "par": 14,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".ba#",
      ".#.#",
      ".A.B",
      "..#."
    ]
  },
  {
    "id": 50,
    "name": "HALF",
    "par": 14,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "...#",
      ".#A.",
      "a#B.",
      "..b#"
    ]
  },
  {
    "id": 51,
    "name": "AURORA",
    "par": 14,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".#b#",
      "a..A",
      "#...",
      "#.#B"
    ]
  },
  {
    "id": 52,
    "name": "CINDER",
    "par": 15,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "a.bA",
      "#.#.",
      "...B",
      "##.#"
    ]
  },
  {
    "id": 53,
    "name": "BEACON",
    "par": 15,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "B.A.",
      "a##.",
      "b#..",
      "#.#."
    ]
  },
  {
    "id": 54,
    "name": "LANTERN",
    "par": 15,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "b..#",
      "a#BA",
      "...#",
      "...#"
    ]
  },
  {
    "id": 55,
    "name": "HARBOUR",
    "par": 15,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#B.A",
      "..#b",
      "..#a",
      "...#"
    ]
  },
  {
    "id": 56,
    "name": "KEEL",
    "par": 16,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "b#..",
      "..#.",
      "Ba..",
      "#.A#"
    ]
  },
  {
    "id": 57,
    "name": "ANCHOR",
    "par": 16,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "a#.#",
      "B#b#",
      "A#..",
      "...."
    ]
  },
  {
    "id": 58,
    "name": "MARINER",
    "par": 16,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".#..",
      "b..#",
      ".#.a",
      "B..A"
    ]
  },
  {
    "id": 59,
    "name": "COMPASS",
    "par": 16,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "a#.#",
      "b..#",
      "B#..",
      "A..."
    ]
  },
  {
    "id": 60,
    "name": "MERIDIAN",
    "par": 16,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#...",
      "..a.",
      "BA#b",
      "#..#"
    ]
  },
  {
    "id": 61,
    "name": "SOLSTICE",
    "par": 17,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#...",
      "..#b",
      ".#AB",
      "a..."
    ]
  },
  {
    "id": 62,
    "name": "ZENITH",
    "par": 17,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#.b#",
      "A.a.",
      ".#B.",
      "...#"
    ]
  },
  {
    "id": 63,
    "name": "LATITUDE",
    "par": 17,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "..A.",
      ".#.#",
      ".B.b",
      "#a.#"
    ]
  },
  {
    "id": 64,
    "name": "CURRENT",
    "par": 17,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "....",
      "b#.A",
      "a...",
      "..#B"
    ]
  },
  {
    "id": 65,
    "name": "DRAUGHT",
    "par": 18,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      ".#bA",
      "..#a",
      ".##B",
      "...."
    ]
  },
  {
    "id": 66,
    "name": "CAVERN",
    "par": 18,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "Ab#.",
      "a#..",
      "B.#.",
      "...."
    ]
  },
  {
    "id": 67,
    "name": "CHASM",
    "par": 18,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "###a",
      "..bA",
      "..##",
      "B..."
    ]
  },
  {
    "id": 68,
    "name": "FISSURE",
    "par": 18,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#..A",
      "..#a",
      "#b#.",
      ".#B."
    ]
  },
  {
    "id": 69,
    "name": "MORAINE",
    "par": 18,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "...A",
      ".##a",
      "..#B",
      "b##."
    ]
  },
  {
    "id": 70,
    "name": "CIRQUE",
    "par": 19,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".#.a",
      "..#b",
      ".#A.",
      "..B#"
    ]
  },
  {
    "id": 71,
    "name": "SERAC",
    "par": 19,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".##b",
      "A.#a",
      ".#.B",
      "...#"
    ]
  },
  {
    "id": 72,
    "name": "CREVASSE",
    "par": 19,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#..a",
      "..#A",
      ".##b",
      "...B"
    ]
  },
  {
    "id": 73,
    "name": "CORNICE",
    "par": 19,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "..#A",
      "#.a.",
      "b.B.",
      ".###"
    ]
  },
  {
    "id": 74,
    "name": "SUMMIT",
    "par": 20,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "Bb##",
      "..#.",
      "Aa..",
      "#..."
    ]
  },
  {
    "id": 75,
    "name": "TRAVERSE",
    "par": 20,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#...",
      ".A#a",
      ".bB#",
      "#..#"
    ]
  },
  {
    "id": 76,
    "name": "ASCENT",
    "par": 20,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#.#.",
      ".bB#",
      ".A#a",
      "#..."
    ]
  },
  {
    "id": 77,
    "name": "PITON",
    "par": 20,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "....",
      "BA#.",
      "#b.#",
      "#..a"
    ]
  },
  {
    "id": 78,
    "name": "BELAY",
    "par": 21,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "...#.",
      "B#...",
      "A##.#",
      ".ba#."
    ]
  },
  {
    "id": 79,
    "name": "CAIRN",
    "par": 21,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "A.b.#",
      ".##a.",
      ".#.#B",
      "....#"
    ]
  },
  {
    "id": 80,
    "name": "BEARING",
    "par": 21,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      "A...#",
      ".#.#B",
      "..#a.",
      "..b.#"
    ]
  },
  {
    "id": 81,
    "name": "POLARIS",
    "par": 22,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      ".....",
      "#.##.",
      "a#...",
      "BbA.#"
    ]
  },
  {
    "id": 82,
    "name": "MIDNIGHT",
    "par": 22,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "一度遠ざかると、別の止まり方が見えてきます。",
      "en": "Moving away can reveal a new place to stop."
    },
    "board": [
      ".....",
      "B.##.",
      "a#...",
      "Ab#.#"
    ]
  },
  {
    "id": 83,
    "name": "LONGNIGHT",
    "par": 23,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "...#",
      "B#aA",
      ".b..",
      "##.#"
    ]
  },
  {
    "id": 84,
    "name": "WHITEOUT",
    "par": 23,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "Aba##",
      ".##..",
      "B#...",
      "...#."
    ]
  },
  {
    "id": 85,
    "name": "BLIZZARD",
    "par": 24,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "Aa..#",
      ".##B#",
      ".#.b.",
      "...#."
    ]
  },
  {
    "id": 86,
    "name": "SQUALL",
    "par": 24,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#....",
      "##.#.",
      "aA#..",
      "..bB#"
    ]
  },
  {
    "id": 87,
    "name": "TEMPEST",
    "par": 25,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "....#",
      ".##.A",
      "..##.",
      ".#baB"
    ]
  },
  {
    "id": 88,
    "name": "GALE",
    "par": 25,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".#abA",
      "..##.",
      ".#..B",
      "...##"
    ]
  },
  {
    "id": 89,
    "name": "PASSAGE",
    "par": 26,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "...#b",
      "...#B",
      ".#a#.",
      ".#..A"
    ]
  },
  {
    "id": 90,
    "name": "ICEFALL",
    "par": 26,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "..b.#",
      "#.#..",
      "..a..",
      ".#A.B"
    ]
  },
  {
    "id": 91,
    "name": "DEEPFROST",
    "par": 27,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "...b#",
      ".#.#B",
      "..#..",
      "#.a.A"
    ]
  },
  {
    "id": 92,
    "name": "COLDIRON",
    "par": 27,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "##...",
      "A.#..",
      "ab...",
      ".B.##"
    ]
  },
  {
    "id": 93,
    "name": "STARFIELD",
    "par": 27,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "..#.#",
      "b....",
      "A#.a.",
      ".B##."
    ]
  },
  {
    "id": 94,
    "name": "NIGHTFALL",
    "par": 27,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".Aba.",
      ".B...",
      ".#.#.",
      "...#."
    ]
  },
  {
    "id": 95,
    "name": "FARSHORE",
    "par": 28,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "a.#b#",
      "....A",
      "...##",
      "#..B."
    ]
  },
  {
    "id": 96,
    "name": "LASTLIGHT",
    "par": 28,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "..a.#",
      "###..",
      "..b..",
      ".#B.A"
    ]
  },
  {
    "id": 97,
    "name": "ENDLESS",
    "par": 28,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "#.A..",
      "..Bb.",
      "a.##.",
      ".#..."
    ]
  },
  {
    "id": 98,
    "name": "THRESHOLD",
    "par": 29,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".#...",
      ".A#.a",
      ".#B..",
      "..b.#"
    ]
  },
  {
    "id": 99,
    "name": "CROSSING",
    "par": 29,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      "A##..",
      "bB.#.",
      "...a.",
      "#...."
    ]
  },
  {
    "id": 100,
    "name": "TILT",
    "par": 31,
    "idea": "Two penguins; branching routes and a verified shortest solution.",
    "hint": {
      "ja": "どちらを先に止めるか、位置関係を見てみよう。",
      "en": "Look at where each penguin can stop the other."
    },
    "board": [
      ".....",
      ".##AB",
      "#.a..",
      ".b..#"
    ]
  }
];
  return { STAGES:STAGES, CHAPTERS:CHAPTERS };
});
